### ISSUE TITLE
Create GameObjects

### ISSUE THREAD

**Issue by gemorlith** [Ebilkill/max-of-empires#2]
Create a class GameObject; it should have an Update, Draw, HandleInput and Parent and Reset. It must be able to find its root. Also create GameObjectList and GameObjectGrid. These should pass update etc. on to the objects. You should be able to remove and add objects to the list without trouble.

**Comment by twijgers** [comment]
Finished it. See master for updates.
Classes were created with proposed methods and properties. Root was called GameWorld for now, but nothing is set in stone :P
Removing and adding functionality added to both the list and the grid.
