### ISSUE TITLE
Improve Grid

### ISSUE THREAD

**Issue by gemorlith** [Ebilkill/max-of-empires#3]
Prerequisites: GameObject, gamestate.

Make sure Grid inherits from GameObjectGrid, improvements:

- HandleInput
- SelectedUnit
- TurnUpdate
- Contains array of Tiles (new class, inherits from GameObject)
- Update etc. should be passed on to each tile.
- Create a property grid in BattleState.

**Comment by gemorlith** [comment]
Should be finished, please review.

**Comment by twijgers** [comment]
Reviewed, made some small changes, merged.
