### ISSUE TITLE
Improve Unit

### ISSUE THREAD

**Issue by gemorlith** [Ebilkill/max-of-empires#5]
Prequisite: Improve Tile.

Make sure Unit has a property Owner, stating which of the two players is the owner of this Unit.
MoveSpeed
MovesLeft
Stats (a new class/struct containing things like (Max)HP, Att, Hit, Dodge, etc.)
HasMoved (returns bool, true if it can no longer be moved)
HasAttacked (returns bool, true if the unit has attacked, and can no longer attack)

In Grid: 
Make sure a Unit can be selected if the current player (create this in current GameState) is its owner.

**Comment by twijgers** [comment]
Fixed. Closing issue
